"""Resumable background reconstruction and morphometry of the remaining stacks."""
import argparse
import fcntl
import json
import os
from pathlib import Path
import subprocess
import shutil
import sys
import time
import traceback

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'results/cpsam_v2_remaining'
CONFIG=ROOT/'config/first5-cpsam-v2.json'


def save(path,value):
    temp=path.with_suffix('.tmp')
    temp.write_text(json.dumps(value,indent=2))
    temp.replace(path)


def samples():
    config=json.loads(CONFIG.read_text())
    data_dir=Path(os.environ.get('ORGANOID_DATA_DIR', config['data_dir']))
    if not data_dir.is_absolute():
        data_dir=ROOT/data_dir
    images=sorted((data_dir/'images').glob('X*.tif'))
    previous={p.parent.name for p in (ROOT/'results/cpsam_v2_first5').glob('run_*/*/complete.json')}
    return [p.stem for p in images if p.stem not in previous]


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dry-run',action='store_true')
    args=parser.parse_args()
    selected=samples()
    if args.dry_run:
        print(json.dumps({'count':len(selected),'first':selected[:5],'last':selected[-5:]},indent=2));return
    OUT.mkdir(parents=True,exist_ok=True)
    lock=(OUT/'worker.lock').open('w')
    try: fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
    except BlockingIOError: raise SystemExit('Another remaining-stack worker is already active')
    import torch
    if not torch.backends.mps.is_available():raise RuntimeError('Apple MPS access required')
    (OUT/'worker.pid').write_text(str(os.getpid()))
    save(OUT/'manifest.json',{'samples':selected,'config':json.loads(CONFIG.read_text()),'masks':'comparison only'})
    state=dict(status='running',pid=os.getpid(),total=len(selected),completed=[],failed={},current=None,started=time.time())
    for i,sample in enumerate(selected,1):
        if (OUT/'STOP_AFTER_CURRENT').exists():
            state['status']='stopped';break
        if shutil.disk_usage(OUT).free < 2*1024**3:
            state['status']='stopped_low_disk'
            print('STOPPED: less than 2 GiB free. Free space, then restart the worker.',flush=True)
            break
        state.update(current=sample,position=i,stage='reconstruction',updated=time.time())
        save(OUT/'status.json',state)
        print(f'\n=== [{i}/{len(selected)}] {sample}: reconstruction; {len(state["completed"])} completed ===',flush=True)
        try:
            subprocess.run([sys.executable,'-u',str(ROOT/'scripts/reconstruct.py'),'predict','--config',str(CONFIG),'--sample',sample,'--output',str(OUT)],cwd=ROOT,check=True)
            state.update(stage='morphology',updated=time.time());save(OUT/'status.json',state)
            print(f'=== {sample}: measuring cell shape and size ===',flush=True)
            subprocess.run([sys.executable,'-u',str(ROOT/'scripts/measure_remaining.py'),sample],cwd=ROOT,check=True)
            # These are disposable caches generated by this batch, not source images or masks.
            for finished in OUT.glob(f'run_*/{sample}/morphology/complete.json'):
                for view in ['xy','xz','yz']:
                    cache=finished.parent.parent/f'{view}.npz'
                    cache.unlink(missing_ok=True)
            state['completed'].append(sample)
            print(f'=== DONE {sample}: {len(state["completed"])}/{len(selected)} remaining stacks analyzed ===',flush=True)
        except Exception as error:
            state['failed'][sample]=str(error);traceback.print_exc()
            print(f'=== FAILED {sample}: continuing to next stack; see traceback above ===',flush=True)
        state['updated']=time.time();save(OUT/'status.json',state)
    else: state['status']='complete_with_errors' if state['failed'] else 'complete'
    state.update(current=None,stage='finished',updated=time.time());save(OUT/'status.json',state)
    print('\nBATCH FINISHED: '+json.dumps(state),flush=True)


if __name__=='__main__':main()
